import "./globals.css";
import { Cormorant } from 'next/font/google'


const cormorant = Cormorant({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
})

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}) {
  return (
    <html lang="en" className={`${cormorant.className} scroll-smooth`}>
      <body className="relative">
        {children}
      </body>
    </html>
  )
}
